name: BuildMachine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  NET-BuildMachine:
    name: .NET BuildMachine
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Install dependencies
        env:
          WORKSPACE: ${{ secrets.WORKSPACE }}
        run: 
          echo "$WORKSPACE"

  Setup-Workspace:
    name: Setup Workspace
    needs: NET-BuildMachine
    runs-on: [ ubuntu-latest ]

    steps:
      - run: echo "Setup-Workspace"


  Checkout-Code:
    name: Checkout Code
    needs: Setup-Workspace
    runs-on: [ ubuntu-latest ]

    steps:
      - run: echo "Checkout-Code"


  Prepare-For-Build:
    name: Prepare For Build
    needs: Checkout-Code
    runs-on: [ ubuntu-latest ]

    steps:
      - run: echo "Prepare-For-Build"
      
  Build:
    name: Build
    needs: Prepare-For-Build
    runs-on: [ ubuntu-latest ]

    steps:
      - run: echo "Build"

  Push-NuGet-Package:
    name: Push-NuGet-Package
    needs: Build
    runs-on: [ ubuntu-latest ]

    steps:
      - run: echo "Push-NuGet-Package"
      
