name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
     - name: hello
       run: echo "Hi from the pipeline" > hola.txt
       
     - name: Display the file content
       run: cat hola
       shell: bash
