name: BuildMachine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  NET-BuildMachine:
    name: .NET BuildMachine
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Install dependencies
        env:
          slnPath: "${{secrets.WORKSPACE}}\\RelayHealth.EncryptionDecryption.sln"
          projectFile: "${{secrets.WORKSPACE}}\\RelayHealth.EncryptionDecryption\\RelayHealth.EncryptionDecryption.csproj"
          nupkgFile: "${{secrets.WORKSPACE}}\\RelayHealth.EncryptionDecryption.*.*.*.*.nupkg"
          nupkgSymbolsFile: "${{secrets.WORKSPACE}}\\RelayHealth.EncryptionDecryption.*.*.*.*.symbols.nupkg"
        run: echo "$slnPath"


  Setup-Workspace:
    name: Setup Workspace
    needs: NET-BuildMachine
    runs-on: [ ubuntu-latest ]

    steps:
      - name: WorkSpace setup
        run: echo "Setup-Workspace"

  Checkout-Code:
    name: Checkout Code
    needs: Setup-Workspace
    runs-on: [ ubuntu-latest ]

    steps:
      - run: echo "Checkout-Code" && ls -flrats


  Prepare-For-Build:
    name: Prepare For Build
    needs: Checkout-Code
    runs-on: [ windows-latest ]

    steps:
      - uses: actions/checkout@master
      - run: echo "Prepare-For-Build" && echo "Restore NuGet Packages"
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'
      - run: nuget restore $slnPath
