name: Test-enviroment-vars

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  NET-BuildMachine:
    name: .NET BuildMachine
    env:
      slnPath: "RelayHealth.EncryptionDecryption.sln"
      projectFile: "RelayHealth.EncryptionDecryption/RelayHealth.EncryptionDecryption.csproj"
      nupkgFile: "RelayHealth.EncryptionDecryption.*.*.*.*.nupkg"
      nupkgSymbolsFile: "RelayHealth.EncryptionDecryption.*.*.*.*.symbols.nupkg"
      id:  id
      version: version
      title: title
      authors: authors
      owners: owners
      description: description
      
    
    runs-on: windows-latest
    
    
    steps:
    - uses: actions/checkout@v2
    - name: Check env variables
      run: SET  
