name: Test-enviroment-vars

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  NET-BuildMachine:
    name: .NET BuildMachine
    env:
      slnPath: "RelayHealth.EncryptionDecryption.sln"
      projectFile: "RelayHealth.EncryptionDecryption/RelayHealth.EncryptionDecryption.csproj"
      nupkgFile: "RelayHealth.EncryptionDecryption.*.*.*.*.nupkg"
      nupkgSymbolsFile: "RelayHealth.EncryptionDecryption.*.*.*.*.symbols.nupkg"
      id:  id_var
      version: version_var
      title: title_var
      authors: authors_var
      owners: owners_var
      description: description_var
      
    
    runs-on: windows-latest
    
    
    steps:
    - uses: actions/checkout@v2
    - name: set env variables
      run: $env:id = $id
           $env:version = $version
           $env:title = $title
           $env:authors = $authors
           $env:owners = $owners
           $env:description = $description
    - name: Check env variables
      run: $env:id 
           $env:version 
           $env:title
           $env:authors
           $env:owners
           $env:description
