name: BuildMachine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  NET-BuildMachine:
    name: .NET BuildMachine
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Install dependencies
        env:
          slnPath: "${{secrets.WORKSPACE}}\\RelayHealth.EncryptionDecryption.sln"
          projectFile: "${{secrets.WORKSPACE}}\\RelayHealth.EncryptionDecryption\\RelayHealth.EncryptionDecryption.csproj"
          nupkgFile: "${{secrets.WORKSPACE}}\\RelayHealth.EncryptionDecryption.*.*.*.*.nupkg"
          nupkgSymbolsFile: "${{secrets.WORKSPACE}}\\RelayHealth.EncryptionDecryption.*.*.*.*.symbols.nupkg"
      - run: echo "$slnPath"


